### ISSUE TITLE
Error while running skypeit

### ISSUE THREAD

**Issue by pkmishra** [staxmanade/skypeit#3]
Following error is thrown...
```
path.js:360
        throw new TypeError('Arguments to path.join must be strings');
        ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Liftoff.invoke (/usr/local/lib/node_modules/skypeit/bin/index.js:74:30)
    at Liftoff.launch (/usr/local/lib/node_modules/skypeit/node_modules/liftoff/index.js:163:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/skypeit/bin/index.js:152:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by staxmanade** [comment]
Hmm - can you open up the file `/usr/local/lib/node_modules/skypeit/bin/index.js` put the following debug console.log lines in and let me know what the output looks like?

Also use the `--debug` parameter to get more information.

## After (with debug code)
```diff
+  console.log('global: ', getUserHome(), globalConfigFileName);
  var globalConfigPath = path.join(getUserHome(), globalConfigFileName);
+  console.log('local: ', env.configBase, globalConfigFileName);
  var localConfigPath = path.join(env.configBase, globalConfigFileName);
  dlog('globalConfigPath:', globalConfigPath);
  dlog('localConfigPath:', localConfigPath);
```

**Comment by pkmishra** [comment]
Here you go

```
Environment is: { cwd: 'XXXX',
  require: [],
  configNameSearch: [ '.skypeitrc' ],
  configPath: null,
  configBase: undefined,
  modulePath: undefined,
  modulePackage: {} }
Cli options are: { _: [ '+1(866)499-7054' ], debug: true }
Liftoff config is: { domain: null,
  _events: {},
  _maxListeners: 10,
  extensions: { '': null },
  searchPaths: [],
  processTitle: 'SkypeIt',
  moduleName: 'skypeit',
  configName: '.skypeitrc' }
global:  /Users/pmishra .skypeitrc
local:  undefined .skypeitrc

path.js:360
        throw new TypeError('Arguments to path.join must be strings');
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Liftoff.invoke (/usr/local/lib/node_modules/skypeit/bin/index.js:75:30)
    at Liftoff.launch (/usr/local/lib/node_modules/skypeit/node_modules/liftoff/index.js:163:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/skypeit/bin/index.js:153:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by staxmanade** [comment]
I just pushed a new version to npm. try `npm install -g skypeit` you should get `v0.0.16` - let me know if this works out for you...

**Comment by pkmishra** [comment]
Yup works fine. Thanks for the great work.
